export const handsFreeCopy = {
  en: {
    pause: 'Pause listening',
    resume: 'Resume listening',
    listening: 'Listening… speak naturally.',
    permission: 'Allow microphone access to start listening.',
    transcribing: 'Understanding your speech…',
    paused: 'Listening paused.',
    help: 'AI voice by ElevenLabs. After you allow the microphone, spoken turns are sent automatically when you pause. Listening pauses during replies, while typing, and when you leave this chat. Profile details still need your confirmation.',
  },
  hi: {
    pause: 'सुनना रोकें',
    resume: 'फिर सुनें',
    listening: 'सुन रहे हैं… बोलिए।',
    permission: 'सुनने के लिए माइक्रोफ़ोन की अनुमति दें।',
    transcribing: 'आपकी बात समझ रहे हैं…',
    paused: 'सुनना रुका है।',
    help: 'ElevenLabs की AI आवाज़। माइक्रोफ़ोन की अनुमति के बाद, बोलकर रुकने पर आपकी बात अपने आप भेजी जाती है। जवाब सुनते समय, लिखते समय और चैट छोड़ने पर सुनना रुकता है। प्रोफ़ाइल की जानकारी की पुष्टि आपको करनी होगी।',
  },
  kn: {
    pause: 'ಆಲಿಸುವುದನ್ನು ನಿಲ್ಲಿಸಿ',
    resume: 'ಮತ್ತೆ ಆಲಿಸಿ',
    listening: 'ಆಲಿಸುತ್ತಿದ್ದೇವೆ… ಮಾತನಾಡಿ.',
    permission: 'ಆಲಿಸಲು ಮೈಕ್ರೋಫೋನ್ ಅನುಮತಿ ನೀಡಿ.',
    transcribing: 'ನಿಮ್ಮ ಮಾತನ್ನು ಅರ್ಥಮಾಡಿಕೊಳ್ಳುತ್ತಿದ್ದೇವೆ…',
    paused: 'ಆಲಿಸುವುದನ್ನು ನಿಲ್ಲಿಸಲಾಗಿದೆ.',
    help: 'ElevenLabs AI ಧ್ವನಿ. ಮೈಕ್ರೋಫೋನ್ ಅನುಮತಿ ನೀಡಿದ ಬಳಿಕ ಮಾತನಾಡಿ ವಿರಾಮ ತೆಗೆದುಕೊಂಡಾಗ ಸಂದೇಶ ತಾನಾಗಿಯೇ ಕಳುಹಿಸಲಾಗುತ್ತದೆ. ಉತ್ತರದ ಸಮಯದಲ್ಲಿ, ಬರೆಯುವಾಗ ಮತ್ತು ಈ ಚಾಟ್ ಬಿಟ್ಟಾಗ ಆಲಿಸುವುದು ನಿಲ್ಲುತ್ತದೆ. ಪ್ರೊಫೈಲ್ ವಿವರಗಳನ್ನು ನೀವು ದೃಢೀಕರಿಸಬೇಕು.',
  },
  ta: {
    pause: 'கேட்பதை நிறுத்து',
    resume: 'மீண்டும் கேள்',
    listening: 'கேட்கிறோம்… இயல்பாகப் பேசுங்கள்.',
    permission: 'கேட்க மைக்ரோஃபோன் அனுமதி வழங்கவும்.',
    transcribing: 'உங்கள் பேச்சைப் புரிந்துகொள்கிறோம்…',
    paused: 'கேட்பது நிறுத்தப்பட்டுள்ளது.',
    help: 'ElevenLabs வழங்கும் AI குரல். மைக்ரோஃபோனை அனுமதித்த பிறகு, பேசிவிட்டு இடைவெளி விடும்போது செய்தி தானாக அனுப்பப்படும். பதில் பேசும்போதும், நீங்கள் தட்டச்சு செய்யும்போதும், இந்த உரையாடலை விட்டு வெளியேறும்போதும் கேட்பது நிறுத்தப்படும். சுயவிவர விவரங்களை நீங்கள் உறுதிப்படுத்த வேண்டும்.',
  },
  ml: {
    pause: 'കേൾക്കുന്നത് നിർത്തുക',
    resume: 'വീണ്ടും കേൾക്കുക',
    listening: 'കേൾക്കുന്നു… സ്വാഭാവികമായി സംസാരിക്കൂ.',
    permission: 'കേൾക്കാൻ മൈക്രോഫോൺ അനുമതി നൽകുക.',
    transcribing: 'നിങ്ങളുടെ സംസാരം മനസ്സിലാക്കുന്നു…',
    paused: 'കേൾക്കുന്നത് നിർത്തിയിരിക്കുന്നു.',
    help: 'ElevenLabs AI ശബ്ദം. മൈക്രോഫോൺ അനുവദിച്ച ശേഷം സംസാരിച്ച് ഇടവേള എടുക്കുമ്പോൾ സന്ദേശം സ്വയം അയയ്ക്കും. മറുപടി പറയുമ്പോഴും ടൈപ്പ് ചെയ്യുമ്പോഴും ഈ ചാറ്റ് വിടുമ്പോഴും കേൾക്കുന്നത് നിർത്തും. പ്രൊഫൈൽ വിവരങ്ങൾ നിങ്ങൾ സ്ഥിരീകരിക്കണം.',
  },
};
